<?php
define("MadMan",true);
require_once("./init.php");
require_once("./lib_admin.php");
$act="";
if(isset($_REQUEST['act']))
{
    $act=$_REQUEST['act'];
}
if($act=="agencies_encashment")
{
    $target="main.php?menu=goods&target=encashment";
    if(isset($_REQUEST['price']))
    {
        $price=abs(intval($_REQUEST['price']));
        if(!empty($price))
        {
            $sql="select * from agencies where id=".$_SESSION['agencies_id'];
            $ag=$db->getRow($sql);
            if(!empty($ag))
            {
                if($price>$ag['income'])
                {
                     JsAlertAndJump("提现金额不能大于您的金额",$target);
                }
                $sql="update agencies set income=(income-$price) where id=".$_SESSION['agencies_id'];
                $res=$db->query($sql);
                if($db->getAffectedRows()>0)
                {
                    $order_sn=time().str_pad(rand(0,99999),5,"0");
                    $fields=array("agencies_id","order_sn","expense_money","expense_status","add_time");
                    $data=array($_SESSION['agencies_id'],$order_sn,$price,0,time());
                    $db->autoExcute("agencies_expense","",$fields,$data);
                    JsAlertAndJump("提现申请已经提交，请耐心等待",$target);
                }
                else
                {
                    JsAlertAndJump("提交失败，请重新尝试",$target);
                }
            }
        }
    }
    else
    {
        JsAlertAndJump("非法数据",$target);
    }
    JsAlertAndJump("非法数据",$target);
}

?>